# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf489e53a646730da8b88a70df75749a8f64f4827ab614f4e0843a8d7520bbfd2472bde3059fff6caafc545296b4948d97059b873eaaf7768b1d75b6367fbe90

test:
  secret_key_base: 8f7f2eeda37762a776980015cc2e1f683f79b75a47fb33a0a7b5acc8ab6bf46c2224c0ac51fc42fabb6e42d88b9c5739a6427508c5aeedafb39e3d886c94a77f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
